pages:
  image: pivotalpa/angular-cli
  stage: deploy
  script:
  - rm -rf node_modules
  - rm -rf dist
  - rm -rf public
  - mkdir -p public
  - npm install
  - ng build --prod --aot
  - mv -f dist/* public/
  artifacts:
    paths:
    - public
  only:
  - master
  