pages:
  image: pivotalpa/angular-cli
  stage: deploy
  script:
  - rm -rf node_modules
  - rm -rf dist
  - rm -rf public
  - npm install
  - ng build --prod=true --aot --deployUrl=https://ohkumaneko.gitlab.io/fortune-telling
  - mv dist/ public/
  artifacts:
    paths:
    - public
  only:
  - master
  