pages:
  image: pivotalpa/angular-cli
  stage: deploy
  script:
  - rm -rf node_modules
  - rm -rf dist
  - rm -rf public
  - mkdir -p public
  - npm install
  - ng build --prod --aot --base-href=/fortune-telling/
  - mv -f dist/ public/
  - pwd
  - ls -la
  - ls -la public/
  artifacts:
    paths:
    - public
  only:
  - master
  